[package]
name = "paq"
version = "2.0.0"
authors = ["Gregory Langlais <_@gregorylanglais.com>"]
edition = "2021"
description = "Hash a directory or file with BLAKE3."
license = "MIT"
readme = "README.md"
keywords = [
  "hash",
  "directory",
  "file",
  "blake3",
  "cryptographic",
]
repository = "https://github.com/gregl83/paq"
homepage = "https://crates.io/crates/paq"

[lib]
name = "paq"
path = "src/lib.rs"

[[bin]]
name = "paq"
path = "src/bin.rs"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true

[[bench]]
name = "hash_buffer_reuse"
harness = false

[[bench]]
name = "hash_by_file_size"
harness = false

[[bench]]
name = "hash_entry_encoding"
harness = false

[[bench]]
name = "hash_large_file"
harness = false

[[bench]]
name = "hash_list_sort"
harness = false

[[bench]]
name = "hash_list_hash"
harness = false

[[bench]]
name = "tree_walk"
harness = false

[[bench]]
name = "functional"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
arrayvec = "0.7.6"
blake3 = { version = "1.8.5", features = ["rayon"] }
clap = { version = "4.6.1", features = ["cargo", "unstable-styles"] }
memmap2 = "0.9.10"
rayon = "1.12"
thiserror = "2.0.20"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.2.2"
criterion = "0.8.2"
jwalk = "0.9.0"

[features]
default = ["test-cleanup"]
test-cleanup = []
