AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for reproducible Rust benchmarking.

Parameters:
  InstanceType:
    Type: String
    Default: c6a.xlarge
    Description: EC2 instance type (e.g., c6a.xlarge for cost-efficiency).
    AllowedValues: [c6a.xlarge, m6i.2xlarge, m6i.4xlarge]

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access.

  GitRepoUrl:
    Type: String
    Default: https://github.com/gregl83/paq.git
    Description: URL of `paq` Git repo containing the project (with flake.nix, hyperfine.sh, etc.).

  BenchmarkDataRepo:
    Type: String
    Default: https://github.com/golang/go.git
    Description: Git repository to use as benchmark test data

  InstanceMarketType:
    Type: String
    Default: on-demand
    Description: 'on-demand' for reliability or spot for cost savings.
    AllowedValues: [spot, on-demand]

  RustVersion:
    Type: String
    Default: "1.82.0"
    Description: Rust version to use for compilation
    AllowedPattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"

  SSHAccessCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to SSH (restrict to your IP for security)
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"

  AutoShutdown:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Automatically shutdown after benchmark completes

Resources:
  BenchmarkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for benchmark instance - SSH access only
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHAccessCIDR
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-benchmark-sg

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore  # For SSM access if needed

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  BenchmarkInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-03c870feb7c37e4ff  # Amazon Linux 2023 AMI 2023.9.20251110.1 x86_64 HVM kernel-6.12
      IamInstanceProfile: !Ref InstanceProfile  # For any needed IAM roles (e.g., S3 access if your benchmarks need it)
      SecurityGroupIds:
        - !Ref BenchmarkSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Set exit immediately, unset vars error, print then exec commands, ensure any failure in pipeline fails
          set -euxo pipefail

          # Set Rust version variable
          RUST_VERSION="${RustVersion}"
          # Set auto-shutdown variable
          AUTO_SHUTDOWN="${AutoShutdown}"

          # Create benchmark group and user
          groupadd benchmark
          useradd -m -s /bin/bash -g benchmark bencher

          # Ensure git is installed
          dnf install -y git

          # Memory management - optimized for benchmarking
          sysctl -w vm.swappiness=1
          sysctl -w vm.dirty_ratio=10
          sysctl -w vm.dirty_background_ratio=3
          sysctl -w vm.dirty_writeback_centisecs=100
          sysctl -w vm.dirty_expire_centisecs=200
          sysctl -w vm.zone_reclaim_mode=0
          sysctl -w vm.min_free_kbytes=131072

          # Transparent Huge Pages - disable for consistent latency
          echo never > /sys/kernel/mm/transparent_hugepage/enabled
          echo never > /sys/kernel/mm/transparent_hugepage/defrag

          # Disable CPU frequency scaling (set to performance mode)
          for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
            if [ -f "$gov" ]; then
              echo performance > "$gov"
            fi
          done

          # Disable CPU turbo boost for consistency
          if [ -f /sys/devices/system/cpu/cpufreq/boost ]; then
            echo 0 > /sys/devices/system/cpu/cpufreq/boost
          fi
          if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
            echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
          fi
          if [ -f /sys/devices/system/cpu/amd_pstate/no_turbo ]; then
            echo 1 > /sys/devices/system/cpu/amd_pstate/no_turbo
          fi

          # Configure I/O scheduler for NVMe (none/noop for best performance)
          for disk in /sys/block/nvme*; do
            if [ -d "$disk/queue" ]; then
              echo none > $disk/queue/scheduler 2>/dev/null || echo noop > $disk/queue/scheduler
              echo 1024 > $disk/queue/nr_requests
              echo 2 > $disk/queue/nomerges
            fi
          done

          # Disable IRQ balance for CPU core isolation
          systemctl stop irqbalance || true
          systemctl disable irqbalance || true

          # Stop unnecessary services to reduce noise
          systemctl stop postfix || true
          systemctl stop atd || true
          systemctl stop crond || true
          systemctl stop rsyslog || true

          # Create benchmark directory on root volume
          mkdir -p /mnt/benchmark
          
          # Set resource limits for benchmark user
          cat >> /etc/security/limits.conf <<EOF
          bencher soft nofile 65536
          bencher hard nofile 65536
          bencher soft nproc 32768
          bencher hard nproc 32768
          bencher soft memlock unlimited
          bencher hard memlock unlimited
          bencher soft cpu unlimited
          bencher hard cpu unlimited
          EOF
          
          # Set mnt ownership
          chown bencher:benchmark /mnt/benchmark
          chmod 755 /mnt/benchmark
          
          # Write and sync to warm up disk
          dd if=/dev/zero of=/mnt/benchmark/warmup bs=1M count=6144 oflag=direct conv=fdatasync
          dd if=/mnt/benchmark/warmup of=/dev/null bs=1M iflag=direct
          sync
          rm -f /mnt/benchmark/warmup
          
          # Run benchmark as dedicated user (bencher)
          su - bencher <<'BENCH'
            set -euxo pipefail
          
            # Install Nix for reproducible environment
            echo "Installing Nix package manager..."
            curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
        
            # Source Nix
            . $HOME/.nix-profile/etc/profile.d/nix.sh
        
            # Enable flakes
            mkdir -p ~/.config/nix
            echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
          
            # Clone benchmark test data
            git clone ${BenchmarkDataRepo} /mnt/benchmark/go
            
            # Clone into paq repo dir
            git clone ${GitRepoUrl} ~/paq && cd ~/paq

            # Build using Nix
            nix build --no-link --print-out-paths
          
            # Run hyperfine benchmarks
            nix develop .#benchmark --command bash -c './benches/hyperfine.sh'
          BENCH

          if [ "$AUTO_SHUTDOWN" = "true" ]; then
            shutdown -h now
          fi
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 35  # GiB; enough for Nix store and Rust builds
            VolumeType: gp3
            Iops: 5000  # Gp3 supports up to 16000; consider more as needed
            Throughput: 1000
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: Benchmark-Instance

Outputs:
  InstanceId:
    Value: !Ref BenchmarkInstance
    Description: The ID of the launched EC2 instance.

  PublicIp:
    Value: !GetAtt BenchmarkInstance.PublicIp
    Description: Public IP for SSH access.